import crypto from "node:crypto";
import type { MemoryMutationProposal } from "../../../contracts/memory.js";
import { MemoryFactStore } from "../../../storage/memory/fact-store.js";
import { MemoryEventStore } from "../../../storage/memory/event-store.js";
import { MemoryJournalStore } from "../../../storage/memory/journal-store.js";
import { MemoryBatchStore } from "../../../storage/memory/batch-store.js";
import { memoryAgentToolMap, validateToolArgs, type MemoryToolContext } from "./memory-agent-tools.js";
import { MEMORY_AGENT_SYSTEM_PROMPT, buildMemoryAgentPrompt, parseAgentReply } from "./memory-agent-prompts.js";
import { writeMemoryRunReport } from "./run-report.js";
export interface MemoryAgentDeps { agentId: string; batchStore: MemoryBatchStore; journalStore: MemoryJournalStore; factStore: MemoryFactStore; eventStore: MemoryEventStore; agentsDir: string; completeText: (req: { systemPrompt: string; prompt: string; maxTokens?: number }) => Promise<string>; assertSessionReadable?: (sessionPath: string) => void; /** 会话 id → JSONL 绝对路径（文件名带时间戳前缀，须由 SessionIndex 解析） */ sessionPathResolver: (sessionId: string) => string; /** 由调用方注入的 runId（resolver 统一事件/报告/回滚的标识）；缺省时内部生成 */ runId?: string; limits?: { maxIterations?: number; maxTokens?: number; maxMinutes?: number }; now?: () => Date; }
export interface MemoryAgentRunResult { runId: string; status: "completed" | "deferred" | "failed"; proposals: readonly MemoryMutationProposal[]; batchIds: readonly string[]; iterations: number; reason?: string; }
export class MemoryAgentRunner { constructor(private readonly deps: MemoryAgentDeps) {} async run(): Promise<MemoryAgentRunResult> { const now = this.deps.now ?? (() => new Date()); const runId = this.deps.runId ?? `run_${crypto.randomUUID()}`; const started = now(); const proposals: MemoryMutationProposal[] = []; const batches = this.deps.batchStore.listPendingBatches(this.deps.agentId); const batchIds = batches.map((b) => b.id); const history: string[] = []; const limits = { maxIterations: 8, maxTokens: 8000, maxMinutes: 10, ...this.deps.limits }; let iterations = 0; let estimate = 0; let malformed = 0; let status: MemoryAgentRunResult["status"] = "deferred"; let reason = "预算耗尽"; try { while (iterations < limits.maxIterations) { if ((now().getTime() - started.getTime()) / 60000 > limits.maxMinutes || estimate > limits.maxTokens) break; iterations += 1; let text: string; try { text = await this.deps.completeText({ systemPrompt: MEMORY_AGENT_SYSTEM_PROMPT, prompt: buildMemoryAgentPrompt({ batches, journalIntents: this.deps.journalStore.listPending(this.deps.agentId), history, budget: `${estimate}/${limits.maxTokens}` }), maxTokens: limits.maxTokens }); } catch { status = "failed"; reason = "模型调用失败"; break; } estimate += text.length / 4; const reply = parseAgentReply(text); if (reply.kind === "malformed") { malformed += 1; history.push("模型输出格式错误，请只输出合法 JSON。"); if (malformed >= 3) break; continue; } malformed = 0; if (reply.kind === "final") { status = "completed"; reason = ""; break; } const tool = memoryAgentToolMap.get(reply.tool); if (!tool || !validateToolArgs(reply.tool, reply.args)) { history.push("工具名称或参数不在白名单内。"); continue; } try { const ctx: MemoryToolContext = { agentId: this.deps.agentId, runId, factStore: this.deps.factStore, eventStore: this.deps.eventStore, journalStore: this.deps.journalStore, batchStore: this.deps.batchStore, agentsDir: this.deps.agentsDir, proposals, assertSessionReadable: this.deps.assertSessionReadable ?? (() => undefined), sessionPathResolver: this.deps.sessionPathResolver, now, }; history.push(`${reply.tool}: ${JSON.stringify(tool.execute(ctx, reply.args as never))}`); } catch { history.push("工具执行失败：参数或资源不可用。"); malformed += 1; if (malformed >= 3) break; } } } catch { status = "failed"; reason = "整理运行失败"; } if (status === "deferred" && iterations >= limits.maxIterations) reason = "超过最大迭代次数"; const completedAt = now().toISOString(); await writeMemoryRunReport({ runId, agentId: this.deps.agentId, agentsDir: this.deps.agentsDir, batchIds, proposals, iterations, status, reason, startedAt: started.toISOString(), completedAt, tokenEstimate: estimate, issues: history.slice(-5) }); return { runId, status, proposals, batchIds, iterations, ...(reason ? { reason } : {}) }; } }
