// ═══════════════════════════════════════════════════════════════
// OpenColorful Phase 12 插件脚手架（plans/phase-12.md §15 / §19.1）
//
// createPlugin 从空目录生成一个可安装的插件骨架：
//   manifest.json（当前 Manifest/API 版本，不复制内部 Server 类型）
//   README.md
//   skills/<name>.md           仅登记、不激活的示例技能
//   dev/scenarios/echo.json    dev loop run-scenario 示例
//   ui/                         页面/组件静态资源占位（iframe 阶段）
//   src/index.js                （runtimeKind=node-process 时）最小 worker 骨架
//
// 生成结果可直接 `plugins dev install <outDir>` 安装。
// ═══════════════════════════════════════════════════════════════

import fs from "node:fs";
import path from "node:path";

import type { ManifestV1, ManifestRuntime, PluginTrust } from "@opencolorful/plugin-protocol";

import { definePlugin } from "./define.js";

export interface CreatePluginOptions {
  /** 插件 id（全局稳定，^[a-z0-9][a-z0-9._-]{0,127}$） */
  readonly id: string;
  readonly name: string;
  /** 缺省 0.1.0 */
  readonly version?: string;
  readonly description?: string;
  readonly authorName?: string;
  /** 缺省 restricted */
  readonly trust?: PluginTrust;
  /** 缺省 bundle；node-process 会附带 src/index.js 最小 worker 骨架 */
  readonly runtimeKind?: ManifestRuntime["kind"];
  /** 生成一个 echo 示例工具（含 dev/scenarios/echo.json） */
  readonly includeTool?: boolean;
  /** 输出目录（缺省 process.cwd()；目标已存在非空且未显式允许则拒绝） */
  readonly outDir?: string;
  readonly overwrite?: boolean;
}

export interface CreatePluginResult {
  readonly dir: string;
  readonly manifest: ManifestV1;
  /** 已生成文件的相对路径列表 */
  readonly files: readonly string[];
}

const GENERATED_MARKER = ".opencolorful-scaffold";

export function createPlugin(options: CreatePluginOptions): CreatePluginResult {
  const outDir = path.resolve(options.outDir ?? process.cwd());
  const id = options.id;
  const name = options.name;
  const version = options.version ?? "0.1.0";
  const runtimeKind = options.runtimeKind ?? "bundle";
  const trust = options.trust ?? "restricted";
  const includeTool = options.includeTool ?? false;

  const runtime: ManifestRuntime =
    runtimeKind === "bundle" ? { kind: "bundle" } : { kind: runtimeKind, entry: "src/index.js" };

  const contributions: ManifestV1["contributions"] = includeTool
    ? {
        tool: [
          {
            id: "echo",
            name: "Echo",
            description: "原样返回输入文本（脚手架示例工具）",
            riskLevel: "low",
            inputSchema: {
              type: "object",
              properties: { text: { type: "string" } },
              required: ["text"],
              additionalProperties: false,
            },
            outputSchema: {
              type: "object",
              properties: { echoed: { type: "string" } },
              required: ["echoed"],
              additionalProperties: false,
            },
          },
        ],
      }
    : {};

  const manifest = definePlugin({
    id,
    name,
    version,
    ...(options.description !== undefined ? { description: options.description } : {}),
    ...(options.authorName !== undefined ? { author: { name: options.authorName } } : {}),
    trust,
    runtime,
    permissions: includeTool ? [{ capability: "tool.register", reason: "脚手架示例工具" }] : [],
    contributions,
    dev: { sourceDir: ".", engines: { node: ">=18" } },
  });

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  } else if (options.overwrite !== true) {
    const entries = fs.readdirSync(outDir);
    const hasForeignContent = entries.some((entry) => entry !== GENERATED_MARKER && !entry.startsWith("."));
    if (hasForeignContent) {
      throw new Error(`输出目录非空且不是脚手架生成：${outDir}（使用 overwrite: true 覆盖）`);
    }
  }

  const files: string[] = [];
  const write = (relative: string, content: string): void => {
    const target = path.join(outDir, relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content, "utf8");
    files.push(relative.replace(/\\/g, "/"));
  };

  write(GENERATED_MARKER, `generated by @opencolorful/plugin-sdk createPlugin\n`);
  write("manifest.json", `${JSON.stringify(manifest, null, 2)}\n`);
  write(
    "README.md",
    `# ${name}\n\n由 @opencolorful/plugin-sdk 脚手架生成。\n\n\`\`\`bash\n# 本地开发循环\nnode scripts/verify-plugin-package.mjs .\n# Server 启动后：\nocf plugins dev install .\n\`\`\`\n`,
  );
  write("skills/example.md", "# Example Skill\n\n示例技能（Phase 12 只登记，不激活）。\n");
  if (includeTool) {
    write(
      "dev/scenarios/echo.json",
      `${JSON.stringify(
        {
          name: "echo-basic",
          description: "调用 echo 工具并断言原样返回",
          destructive: false,
          steps: [
            { kind: "invoke-tool", tool: "echo", args: { text: "hello" }, expect: { result: { echoed: "hello" }, requireConfirmation: false } },
          ],
        },
        null,
        2,
      )}\n`,
    );
  }
  write("ui/placeholder.txt", "iframe UI 阶段占位（T8/T10）。\n");
  if (runtimeKind === "node-process") {
    write(
      "src/index.js",
      `// 最小 Node worker 骨架（@opencolorful/plugin-runtime）
// 将 manifest.json 的 runtime.kind 声明为 "node-process" 后即可运行。
import { createRuntimeServer } from "@opencolorful/plugin-runtime";

const server = createRuntimeServer({});

server.registerMethod("echo", (params) => {
  const text = typeof params === "object" && params !== null && "text" in params
    ? String(params.text) : "";
  return { echoed: text };
});

server.start().catch((error) => {
  console.error("worker 启动失败", error);
  process.exit(1);
});
`,
    );
  }

  return { dir: outDir, manifest, files };
}
